blocked_pointers:
  - 0x801fdcc0
  - 0x801fdd94

forced_types:
  0x801fc300: FUNCTION # TRKExceptionHandler
  0x801fc460: FUNCTION # TRKInterruptHandlerEnableInterrupts

sdata_sizes:
  - [0x803fae48, 8]
  - [0x803fadc0, 8]
  - [0x803fb4e0, 8]
  - [0x803fb4f0, 8]