forced_types:
  0x801fc300: FUNCTION # TRKExceptionHandler
  0x801fc460: FUNCTION # TRKInterruptHandlerEnableInterrupts

trim_ctors: true

symbol_aligns:
  0x802eaa60: 32 # align pBuffer in demoinit.cpp to 32 bytes
  0x802d4dc0: 32 # Header from OSReboot.c
  0x803fb1a0: 32 # Gbase from THPDec.c
  0x803fb1c0: 32 # Gwid from THPDec.c
  0x803fb1e0: 32 # Gq from THPDec.c
  0x803f04c0: 32 # ActivePlayer from THPPlayer.c