forced_types:
  0x801fc300: FUNCTION # TRKExceptionHandler
  0x801fc460: FUNCTION # TRKInterruptHandlerEnableInterrupts

trim_ctors: true

symbol_aligns:
  0x802eaa60: 32 # align pBuffer in demoinit.cpp to 32 bytes
  0x802d4dc0: 32 # Header from OSReboot.c
  0x803fb1a0: 32 # Gbase from THPDec.c
  0x803fb1c0: 32 # Gwid from THPDec.c
  0x803fb1e0: 32 # Gq from THPDec.c
  0x803f04c0: 32 # ActivePlayer from THPPlayer.c
  0x803fb0e0: 32 # Ydchuff from THPDec.c
  0x803fb100: 32 # Udchuff from THPDec.c
  0x803fb120: 32 # Vdchuff from THPDec.c
  0x803fb140: 32 # Yachuff from THPDec.c
  0x803fb160: 32 # Uachuff from THPDec.c
  0x803fb180: 32 # Vachuff from THPDec.c
  0x803fb1a0: 32 # Gbase from THPDec.c
  0x803fb1c0: 32 # Gwid from THPDec.c
  0x803fb1e0: 32 # Gq from THPDec.c
  # 0x80271CA0: 32 # ? CardData from CARDUnlock.c
  # 0x802c38e0: 32 # ? __AXStudio from AXSPB.c
  # 0x8026ce20: 32 # ? __AXCompressorTable from AXComp.c
  0x8038dde0: 32 # effectData from ModelGC.cpp
  # 0x80276A80: 32 # rawCaptureTexData from Material_GC.cpp
  # 0x80298020: 32 # XFontBitmap
  # 0x802DBC20: 32 # __THPIDCTWorkspace
  # 0x8036F760: 32 # materialIni from Material_GC.cpp
  # 0x8036F7A0: 16 # restorationTexObj
  # 0x803F33C0: 32 # lo$433 from View_GC.cpp
  # 0x803F3420: 32 # ortho_old from View_GC.cpp
  # 0x803FAFD8: 8 # bound_32KHz
  # 0x803FB4E0: 8 # timePadLast$863 from System_GC.cpp
  # 0x803FB4F0: 8 # timeDiscClosed$866 from System_GC.cpp