path: orig/main.dol
r13: 0x803fb860
r2: 0x804035a0

section_defs:
    text:
      - name: .init
      - name: .text
    data:
      - name: extab
        attr: a
      - name: extabindex
        attr: a
      - name: .ctors
        balign: 0
      - name: .dtors
        balign: 0
      - name: .rodata
      - name: .data
      - name: .sdata
      - name: .sdata2
    bss:
      - name: .bss
      - name: .sbss
      - name: .sbss2
        nobits: true