

# any files that have extra flags are placed here with the flags
# these flags will be added to the default flags

common/gc/THPAudioDecode.c:
    .flags: "-lang c"

Dolphin/os/__start.c:
    .flags: "-lang c"
    .compiler: "1.2.5"

Runtime/abort_exit.c:
   .flags: "-lang=c"