

# any files that have extra flags are placed here with the flags
# these flags will be added to the default flags

ty/source/DataVal.cpp:
    .flags: "-pool off"

ty/source/GameObject.cpp:
    .flags: "-pool off"

#common/Source/Translation.cpp:
#    .flags: "-pool off"

ty/source/RangeCheck.cpp:
    .flags: "-pool off"

#ty/source/props/StaticProp.cpp:
#    .flags: "-pool off"