
from pathlib import Path

from typing import Dict, List, Tuple

from collections import Counter

from tools.project import (
    Object,
    ProjectConfig
)

import re
import os

from itertools import zip_longest

script_dir = os.path.dirname(os.path.realpath(__file__))
root_dir = os.path.abspath(os.path.join(script_dir, ".."))

ORIG_ELF = os.path.join(root_dir, "orig", "GTYE69", "files", "TY_REL.elf")

# This file was generated by a custom pyelftools readelf.py in order to include entire symbol name
# and symbol sizes as decimal rather than hex
ORIG_ELF_SYMBOLS = os.path.join(root_dir, "orig", "GTYE69", "extracted_map", "TY_REL.map.txt")

BINUTILS_PATH = os.path.join(root_dir, "build", "binutils")

USE_BINUTILS = os.path.exists(BINUTILS_PATH)

if not os.path.exists(BINUTILS_PATH):
    pass
    # print(f"Cannot check symbols! Binutils: {BINUTILS_PATH} does not exist.")
    # exit(1)

# nm to get full symbol name as readelf limits after so many characters
NM = os.environ.get("NM", os.path.join(BINUTILS_PATH, "powerpc-eabi-nm.exe"))
READELF = os.environ.get("READELF", os.path.join(BINUTILS_PATH, "powerpc-eabi-readelf.exe"))

if not os.path.exists(ORIG_ELF_SYMBOLS):
    print(f"Cannot check_symbols! {ORIG_ELF_SYMBOLS} does not exist.")
    exit(1)

# Use a custom readelf.py in order to get all characters in a symbol (limits in order to match readelf)
CUSTOM_READELF_PY_PATH = ""
if not os.path.exists(CUSTOM_READELF_PY_PATH):
    print(f"Cannot check_symbols! {CUSTOM_READELF_PY_PATH} does not exist.")
    exit(1)

HANDLE_ANON_STATIC_NAMES = True

def compare_sym_names(lhs: str, rhs: str) -> bool:
    if HANDLE_ANON_STATIC_NAMES:
        ANON_LITERAL = r"@(\d+)"

        FUNCTION_STATIC = r"(\S+)\$(\d+)"

        lhs_match = re.match(ANON_LITERAL, lhs)
        rhs_match = re.match(ANON_LITERAL, rhs)

        # group 0 is the full string, group 1 would be \d+
        is_lhs_anon_lit = lhs_match and len(lhs_match.groups()) > 1
        is_rhs_anon_lit = rhs_match and len(rhs_match.groups()) > 1

        # if both are anon literals, names match
        # if one or the other but not both are anon literals, names do not match
        if is_lhs_anon_lit and is_rhs_anon_lit:
            return True
        elif is_lhs_anon_lit and (not is_rhs_anon_lit):
            return False
        elif (not is_lhs_anon_lit) and is_rhs_anon_lit:
            return False

        lhs_match = re.match(FUNCTION_STATIC, lhs)
        rhs_match = re.match(FUNCTION_STATIC, rhs)

        # group 0 is the full string, group 1 would be \d+
        is_lhs_func_static = lhs_match and len(lhs_match.groups()) > 1
        is_rhs_func_static = rhs_match and len(rhs_match.groups()) > 1

        if is_lhs_func_static and is_rhs_func_static:
            # if both are func statics, need to check the name
            return re.sub(FUNCTION_STATIC, r"\1\$", lhs) == re.sub(FUNCTION_STATIC, r"\1\$", rhs)

    return lhs == rhs

class ParsedLine:
    def __init__(self, text: str, parsed_nm_info: str|None = None):
        LINE_RE = r"^\s+(\d+):\s+([0-9a-fA-F]+)\s+(\d+|(?:0x)?[0-9a-fA-F]+)\s+(NOTYPE|FUNC|FILE|SECTION|OBJECT)\s+(LOCAL|GLOBAL)\s+(DEFAULT)\s+(\d+|UND|ABS)\s+(\S+)$"

        matches = re.match(LINE_RE, text)
        if not matches:
            self.valid = False
            return

        self.valid = True
        self.num = matches.group(1)
        self.addr = matches.group(2)
        self.size = matches.group(3)
        self.type = matches.group(4)
        self.bind = matches.group(5)
        self.vis = matches.group(6)
        self.index = matches.group(7)

        if parsed_nm_info:
            self.name = parsed_nm_info[self.addr]
        else:
            self.name = matches.group(8)

        return

    def __eq__(self, other):
        name_cond = self.name == other.name
        return (1 and
            # self.num == other.num and
            self.addr == other.addr and
            self.size == other.size and
            self.type == other.type and
            self.bind == other.bind and
            self.vis == other.vis and
            self.index == other.index and
            ((self.type == "OBJECT" and other.type == "OBJECT") or compare_sym_names(self.name, other.name))
        )
    
    def __str__(self):
        """Returns a human-readable string representation of the parsed line."""
        if not self.valid:
            return "<Invalid ParsedLine>"
        
        return (f"Line {self.num}: {self.name} "
                f"[Addr: {self.addr}, Size: {self.size}, "
                f"Type: {self.type}, Bind: {self.bind}, Index: {self.index}]")
    
    def __repr__(self):
        """Used when the object is inside a container like a list."""
        if not self.valid:
            return "<ParsedLine (Invalid)>"
        return f"<ParsedLine: {self.name} ({self.type})>"

class SymbolFile:
    def __init__(self, line: ParsedLine):
        self.line = line

        self.addr = line.addr
        self.name = line.name

        self.sections: List[ParsedLine] = []
        self.symbols: List[ParsedLine] = []
        return

    def addSection(self, line: ParsedLine):
        self.sections.append(line)

    def addSymbol(self, line: ParsedLine):
        self.symbols.append(line)
    
    def __str__(self):
        """Returns a formatted overview of the file, its sections, and symbols."""
        output = [f"File: {self.name} (Address: {self.addr})"]
        
        output.append(f"  Sections ({len(self.sections)}):")
        for sec in self.sections:
            output.append(f"    - {sec}")
            
        output.append(f"  Symbols ({len(self.symbols)}):")
        for sym in self.symbols:
            output.append(f"    - {sym}")
            
        return "\n".join(output)
    
    def __repr__(self):
        """Used when the object is inside a container like a list."""
        return f"<SymbolFile: {self.name} | sections: {len(self.sections)}, symbols: {len(self.symbols)}>"

def count_sections_by_name(parsed_lines: List[ParsedLine]) -> Counter:
    """Counts occurrence of section names across a list of ParsedLine objects."""
    return Counter(
        line.name
        for line in parsed_lines
        if line.valid and line.type == "SECTION"
    )

def clean_name(name: str) -> str:
    """Strips @ $ followed by digits from the end of a symbol name."""
    return re.sub(r"[\$@]\d+", "", name)

ONLY_SHOW_DIFFS = True

def is_out_of_order(reference: List[ParsedLine], target: List[ParsedLine]) -> bool:
    ref_sequence = [(clean_name(line.name), line.type, line.addr) for line in reference if line.valid]
    target_sequence = [(clean_name(line.name), line.type, line.addr) for line in target if line.valid]
    
    return ref_sequence != target_sequence

class DiffFileResult:
    def __init__(self, orig, built):
        self.orig_file: SymbolFile = orig
        self.built_file: SymbolFile = built

        self.differing_sections: List[Tuple[ParsedLine, ParsedLine]] = []

        for orig_sect, build_sect in zip_longest(orig.sections, built.sections, fillvalue=None):
            if not build_sect or not (orig_sect == build_sect):
                self.differing_sections.append((orig_sect, build_sect))

        self.differing_syms: List[ParsedLine] = []

        for orig_sym, build_sym in zip_longest(orig.symbols, built.symbols, fillvalue=None):
            if not build_sym or not (orig_sym == build_sym):
                self.differing_syms.append((orig_sym, build_sym))

        print(f"Diffing {orig.name} and {built.name}")

        print("Sections:")
        for section_diff in self.differing_sections:
            print(f"    {section_diff[0]}, {section_diff[1]}")

        print("Symbols:")
        for symbol_diff in self.differing_syms:
            print(f"    {symbol_diff[0]}, {symbol_diff[1]}")

    def has_diffs(self) -> bool:
        return len(self.differing_sections) > 0 or len(self.differing_syms) > 0

def compare_sym_files(symfile0: SymbolFile, symfile1: SymbolFile):
    if symfile0.name != symfile1.name:
        print(f"{symfile0.name} does not match {symfile1.name}")
        return False
    
    if len(symfile0.sections) != len(symfile1.sections):
        return False
    
    if len(symfile0.symbols) != len(symfile1.symbols):
        return False

    if is_out_of_order(symfile0.symbols, symfile1.symbols) == True:
        return False

    return True

def find_file_entry(files: List[SymbolFile], name: str) -> SymbolFile:
    return [f for f in files if f.name == name][0]

IGNORE_TU_SYM_ORDER = True

def check_all_sym_files(files0: List[SymbolFile], files1: List[SymbolFile], completed: Dict[str, Object]):

    if len(files0) != len(files1):
        print("Binaries have different file count")
        return False

    diff_files: Tuple[SymbolFile, SymbolFile] = []

    for a, b in zip(files0, files1):

        if a.name not in completed and b.name not in completed:
            continue

        if a.name != b.name:
            print(f"{a.name} does not match {b.name}")

            # if the tu names do not match and we shold not ignore tu order, skip
            if not IGNORE_TU_SYM_ORDER:
                continue

            # if tu names do not match
            # find the matching entry in the built symbol table for the orig tu
            b = find_file_entry(files1, a.name)
    
        diff_res: DiffFileResult = DiffFileResult(a, b)
        if diff_res.has_diffs() or compare_sym_files(a, b) == False:
            diff_files.append((a, b))

    stray_mwcat_entries: List[str] = []
    for a, b in diff_files:
        if len(a.sections) != len(b.sections):
            orig_sects: Counter = count_sections_by_name(a.sections)
            build_sects: Counter = count_sections_by_name(b.sections)

            if ".mwcats.text" in orig_sects:
                if orig_sects[".mwcats.text"] > build_sects[".mwcats.text"]:
                    stray_mwcat_entries.append(a.name)
            
        print(f"{a}\nis different than\n{b}")

    print(f"{len(diff_files)} files different!")
    print(f"{len(stray_mwcat_entries)} .mwcats.text diffs! After {stray_mwcat_entries}")
    
    return len(diff_files) == 0

def parse_nm(text: str) -> Dict[str, str]:
    res = {}

    for line in text:
        parts = line.split()
        if len(parts) == 3:
            res[parts[0]] = parts[2]

    return res

def parse_sym_text(readelf_text: str, nm_text: str|None = None) -> List[SymbolFile]:

    text = readelf_text[1:]

    current_file: SymbolFile = None

    files: List[SymbolFile] = []

    for line in text:
        parsed_line: ParsedLine = ParsedLine(line, nm_text)

        if not parsed_line.valid:
            continue

        if parsed_line.bind == "GLOBAL":
            break

        if parsed_line.type == "FILE":
            if not current_file:
                # found file for the first time
                current_file = SymbolFile(parsed_line)
                files.append(current_file)
            elif current_file:
                current_file = SymbolFile(parsed_line)
                files.append(current_file)
        elif parsed_line.type == "SECTION":
            current_file.addSection(parsed_line)
        elif parsed_line.type == "OBJECT" or parsed_line.type == "FUNC" or parsed_line.type == "NOTYPE":
            current_file.addSymbol(parsed_line)

    return files

def parse_sym_file(filepath: str) -> List[SymbolFile]:
    sym_lines = ""

    with open(filepath, "rt") as fd:
        sym_lines = fd.readlines()
    
    return parse_sym_text(sym_lines)

def read_elf_symbols(elf_path) -> Tuple[str, str]:
    import subprocess

    if USE_BINUTILS:
        readelf_cmd = [READELF, "--symbols", elf_path]
    else:
        readelf_cmd = ["python", CUSTOM_READELF_PY_PATH, "--symbols", elf_path]

    readelf_result = subprocess.run(readelf_cmd, capture_output=True, text=True, shell=True)

    nm_result = None
    if USE_BINUTILS:
        nm_cmd = [NM, "-p", elf_path]
        nm_result = subprocess.run(nm_cmd, capture_output=True, text=True, shell=True)

    if readelf_result.returncode == 0:
        if nm_result and nm_result.returncode == 0:
            return (readelf_result.stdout.splitlines()[2:], nm_result.stdout.splitlines()[2:])
        else:
            return (readelf_result.stdout.splitlines()[2:], "")
    else:
        return ("", "")

def check_symbols(config: ProjectConfig):
    import os

    orig_files = parse_sym_file(ORIG_ELF_SYMBOLS)
    elf_file_path = os.path.join(os.getcwd(), config.out_path(), "main.elf").replace("\\", "/")

    readelf_out, nm_out = read_elf_symbols(elf_file_path)

    parsed_nm_info = None
    if nm_out != "":
        parsed_nm_info = parse_nm(nm_out)

    built_files = parse_sym_text(readelf_out, parsed_nm_info)

    objects: Dict[str, Object] = config.objects()

    completed_objs: Dict[str, Object] = {}

    for obj_name in objects:
        if objects[obj_name].completed:
            completed_objs[obj_name.split('/')[-1]] = objects[obj_name]

    are_same = check_all_sym_files(orig_files, built_files, completed_objs)
    if are_same:
        print("Symbol Tables Match!")
    else:
        print("Symbol Tables Differ!")
